export const KEY_DATA = [
  [
    {
      ru: '`',
      en: '`',
      functional: true,
      additional: false,
      additionalValue: '',
    },
    {
      ru: '1',
      en: '1',
      functional: false,
      additional: false,
      additionalValue: '',
    },
    {
      ru: '2',
      en: '2',
      functional: false,
      additional: false,
      additionalValue: '',
    },
    {
      ru: '3',
      en: '3',
      functional: false,
      additional: false,
      additionalValue: '',
    },
    {
      ru: '4',
      en: '4',
      functional: false,
      additional: false,
      additionalValue: '',
    },
    {
      ru: '5',
      en: '5',
      functional: false,
      additional: false,
      additionalValue: '',
    },
    {
      ru: '6',
      en: '6',
      functional: false,
      additional: false,
      additionalValue: '',
    },
    {
      ru: '7',
      en: '7',
      functional: false,
      additional: false,
      additionalValue: '',
    },
    {
      ru: '8',
      en: '8',
      functional: false,
      additional: false,
      additionalValue: '',
    },
    {
      ru: '9',
      en: '9',
      functional: false,
      additional: false,
      additionalValue: '',
    },
    {
      ru: '0',
      en: '0',
      functional: false,
      additional: false,
      additionalValue: '',
    },
    {
      ru: '-',
      en: '-',
      functional: false,
      additional: false,
      additionalValue: '',
    },
    {
      ru: '=',
      en: '=',
      functional: false,
      additional: false,
      additionalValue: '',
    },
    {
      ru: 'Backspace',
      en: 'Backspace',
      functional: true,
      additional: false,
      additionalValue: '',
    },
  ],
  [
    {
      ru: 'Tab',
      en: 'Tab',
      functional: true,
      additional: false,
      additionalValue: '',
    },
    {
      ru: 'Й',
      en: 'Q',
      functional: false,
      additional: false,
      additionalValue: '',
    },
    {
      ru: 'Ц',
      en: 'W',
      functional: false,
      additional: false,
      additionalValue: '',
    },
    {
      ru: 'У',
      en: 'E',
      functional: false,
      additional: false,
      additionalValue: '',
    },
    {
      ru: 'К',
      en: 'R',
      functional: false,
      additional: false,
      additionalValue: '',
    },
    {
      ru: 'Е',
      en: 'T',
      functional: false,
      additional: false,
      additionalValue: '',
    },
    {
      ru: 'Н',
      en: 'Y',
      functional: false,
      additional: false,
      additionalValue: '',
    },
    {
      ru: 'Г',
      en: 'U',
      functional: false,
      additional: false,
      additionalValue: '',
    },
    {
      ru: 'Ш',
      en: 'I',
      functional: false,
      additional: false,
      additionalValue: '',
    },
    {
      ru: 'Щ',
      en: 'O',
      functional: false,
      additional: false,
      additionalValue: '',
    },
    {
      ru: 'З',
      en: 'P',
      functional: false,
      additional: false,
      additionalValue: '',
    },
    {
      ru: 'Х',
      en: '[',
      functional: false,
      additional: false,
      additionalValue: '',
    },
    {
      ru: 'Ъ',
      en: ']',
      functional: false,
      additional: false,
      additionalValue: '',
    },
    {
      ru: 'DEL',
      en: 'DEL',
      functional: true,
      additional: false,
      additionalValue: '',
    },
  ],
  [
    {
      ru: 'Caps Lock',
      en: 'Caps Lock',
      functional: true,
      additional: false,
      additionalValue: '',
    },
    {
      ru: 'Й',
      en: 'A',
      functional: false,
      additional: false,
      additionalValue: '',
    },
    {
      ru: 'Ц',
      en: 'S',
      functional: false,
      additional: false,
      additionalValue: '',
    },
    {
      ru: 'У',
      en: 'D',
      functional: false,
      additional: false,
      additionalValue: '',
    },
    {
      ru: 'К',
      en: 'F',
      functional: false,
      additional: false,
      additionalValue: '',
    },
    {
      ru: 'Е',
      en: 'G',
      functional: false,
      additional: false,
      additionalValue: '',
    },
    {
      ru: 'Н',
      en: 'H',
      functional: false,
      additional: false,
      additionalValue: '',
    },
    {
      ru: 'Н',
      en: 'J',
      functional: false,
      additional: false,
      additionalValue: '',
    },
    {
      ru: 'Н',
      en: 'K',
      functional: false,
      additional: false,
      additionalValue: '',
    },
    {
      ru: 'Н',
      en: 'L',
      functional: false,
      additional: false,
      additionalValue: '',
    },
    {
      ru: 'Н',
      en: ';',
      functional: false,
      additional: false,
      additionalValue: '',
    },
    {
      ru: 'Н',
      en: `'`,
      functional: false,
      additional: false,
      additionalValue: '',
    },
    {
      ru: 'ENTER',
      en: 'ENTER',
      functional: true,
      additional: false,
      additionalValue: '',
    },
  ],
  [
    {
      ru: 'Shift',
      en: 'Shift',
      functional: true,
      additional: false,
      additionalValue: '',
    },
    {
      ru: '\\',
      en: '\\',
      functional: false,
      additional: false,
      additionalValue: '',
    },
    {
      ru: '2',
      en: 'Z',
      functional: false,
      additional: false,
      additionalValue: '',
    },
    {
      ru: '3',
      en: 'X',
      functional: false,
      additional: false,
      additionalValue: '',
    },
    {
      ru: '4',
      en: 'C',
      functional: false,
      additional: false,
      additionalValue: '',
    },
    {
      ru: '5',
      en: 'V',
      functional: false,
      additional: false,
      additionalValue: '',
    },
    {
      ru: '6',
      en: 'B',
      functional: false,
      additional: false,
      additionalValue: '',
    },
    {
      ru: '7',
      en: 'N',
      functional: false,
      additional: false,
      additionalValue: '',
    },
    {
      ru: '8',
      en: 'M',
      functional: false,
      additional: false,
      additionalValue: '',
    },
    {
      ru: '9',
      en: ',',
      functional: false,
      additional: false,
      additionalValue: '',
    },
    {
      ru: '0',
      en: '.',
      functional: false,
      additional: false,
      additionalValue: '',
    },
    {
      ru: '-',
      en: '/',
      functional: false,
      additional: false,
      additionalValue: '',
    },
    {
      ru: 'Shift',
      en: 'Shift',
      functional: true,
      additional: false,
      additionalValue: '',
    },
  ],
  [
    {
      ru: 'CTRL',
      en: 'CTRL',
      functional: true,
      additional: false,
      additionalValue: '',
    },
    {
      ru: 'Win',
      en: 'Win',
      functional: true,
      additional: false,
      additionalValue: '',
    },
    {
      ru: 'ALT',
      en: 'ALT',
      functional: true,
      additional: false,
      additionalValue: '',
    },
    {
      ru: ' ',
      en: ' ',
      functional: false,
      additional: false,
      additionalValue: '',
    },
    {
      ru: 'ALT',
      en: 'ALT',
      functional: true,
      additional: false,
      additionalValue: '',
    },
    {
      ru: 'CTRL',
      en: 'CTRL',
      functional: true,
      additional: false,
      additionalValue: '',
    },
    {
      ru: '6',
      en: 'B',
      functional: false,
      additional: false,
      additionalValue: '',
    },
    {
      ru: '7',
      en: 'N',
      functional: false,
      additional: false,
      additionalValue: '',
    },
    {
      ru: '8',
      en: 'M',
      functional: false,
      additional: false,
      additionalValue: '',
    },
  ],
];
